version: "{build}"

environment:
  matrix:
    # For regular jobs, such as push, pr and etc.
    - job_name: Linux
      appveyor_build_worker_image: ubuntu2004
      GOARCH: amd64
    - job_name: MacOS
      appveyor_build_worker_image: macos-bigsur
      GOARCH: amd64
    - job_name: Windows
      appveyor_build_worker_image: Visual Studio 2019
      GOARCH: amd64

for:
  - # Linux and MacOS
    skip_tags: true
    matrix:
      only:
        - job_name: Linux
        - job_name: MacOS

    install:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.2
      - go mod vendor

    test_script:
      - golangci-lint cache clean
      - make check

  - # Windows
    skip_tags: true
    build: off
    matrix:
      only:
        - job_name: Windows

    environment:
      matrix:
        - GOARCH: amd64

    install:
      - choco install make
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2
      - go mod vendor
      - set PATH=C:\Users\appveyor\go\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%

    test_script:
      - set GO111MODULE=on
      - golangci-lint cache clean
      - make check-windows
